language: node_js
node_js:
  - 7
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - unzip
services:
  - docker
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: Yc4UTNmINFGCeRKl52lFVPFPOshGtA95mfy+KWxhG/mhyIIgrkHun+LVpwR+A4jrD3gW0PrA0O23UBTmmdkWg8kbWGhuiJfaoguNOZczOFXh2lnlKfBX3mqe/v9t7wNFArNoftAxVz0j/VTkoEuJfTX/AoSMHZ3HxI9lWavZMybFCw6o7DtUEaSSbRd5B+mPzTIrUrOanXz22jP9VeigpX2DwhfFJhPYS4xfFZ31/yxkUl4u41JdMpP+lK+wLbMN0okJaGHXon/iqXiwvUZsHlLVlMUG8OQiBvVTrDCSt0BZMkYsxlKBwveJiSWo1b/WYyGRIamWtjgYY6crTT16Zns2lPx7pYZte2iww/xQvZuQ29t7wRqWFqvpOO2nK1vtZsMCk1fjIK1FBvhd/eaRdjvmpEqSDbAYgphtf7CBuftnSk3p0zw8tHjTJ32gym3JGnP8rFLqwplz5wJc6pgmfCrWOrfF2QEYH2x7FlgiEadr4Ckx5cKbo/OCx7sRUGXhKShqSFh9bAD1niXhyPrUCDo6c9MOv73zyLtc4QquB8dSD2veCok/TMPw53N6ggS3lSItxcaZXchYWQUd1SuGSs+zaDnOJ4qTmFDlxFJKOxFzTia6Wx0oG2naG5mqZeX7rNMztw3w43Qoy3C9djx9e62wnOvjSlT8kD8cv+xiXEk=
jobs:
  include:
    - stage: build and test
      script: npm run eslint
    - stage: build docker image
      script:
        - |
          openssl aes-256-cbc -K $encrypted_c2aec72b3ee3_key -iv $encrypted_c2aec72b3ee3_iv -in secrets.zip.enc -out secrets.zip -d && \
          unzip secrets.zip && \
          docker login -u $DOCKER_AZURE_USER -p $DOCKER_AZURE_PASS $DOCKER_REPO_AZURE && \
          docker build -t $DOCKER_REPO_AZURE/breakout-frontend:$(basename $TRAVIS_BRANCH) . && \
          docker push $DOCKER_REPO_AZURE/breakout-frontend:$(basename $TRAVIS_BRANCH) && \
          rm "/home/${USER}/.docker/config.json"
stages:
  - build and test
  - build docker image
