name: Test and build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run eslint
  build_and_push_docker_to_registry:
    name: Push Docker image to Registry
    runs-on: ubuntu-latest
    needs: [build_and_test]
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV     
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: breakout/breakout-frontend:${{ env.BRANCH }}${{ ( env.BRANCH == 'master' && ',breakout/breakout-frontend:latest') || '' }}
